import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { config } from "dotenv";

config({ path: ".env.local" });

//   SCRAPER_INTEGRATION=1 SCRAPER_TEST_USER_ID=<id> npx vitest run src/digest
const isEnabled =
  process.env.SCRAPER_INTEGRATION === "1" && Boolean(process.env.SCRAPER_TEST_USER_ID);
const describeIntegration = isEnabled ? describe : describe.skip;

const userId = `digest-test-${Date.now()}`;

async function addJob(sourceJobId: string, title: string) {
  const { db } = await import("@/lib/db");
  const { insertJobs } = await import("@/jobs/jobs.db");

  const [job] = await insertJobs(db, userId, [
    {
      sourceJobId,
      source: "remoteok",
      title,
      company: "Test Co",
      jobUrl: `https://example.com/${sourceJobId}`,
      companyUrl: null,
      location: "Remote",
      salary: null,
      description: null,
      postedAt: new Date(),
      workType: "unknown",
      isRemote: true,
      tags: null,
      attributionText: null,
      attributionUrl: null,
    },
  ]);
  return job;
}

beforeAll(async () => {
  if (!isEnabled) return;
  const { db } = await import("@/lib/db");
  const { users, userSettings } = await import("@/lib/db/schema");
  const { createId } = await import("@paralleldrive/cuid2");

  await db.insert(users).values({
    id: userId,
    name: "Digest Test",
    email: `${userId}@invalid.test`,
    emailVerified: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  });
  await db.insert(userSettings).values({
    id: createId(),
    userId,
    dailyDigestEnabled: true,
  });
});

afterAll(async () => {
  if (!isEnabled) return;
  const { db } = await import("@/lib/db");
  const { users } = await import("@/lib/db/schema");
  const { eq } = await import("drizzle-orm");

  await db.delete(users).where(eq(users.id, userId));
});

describeIntegration("digest window (live, writes to db)", () => {
  it("lists an account that opted in", async () => {
    const { db } = await import("@/lib/db");
    const { getDigestSubscribers } = await import("./digest.db");

    const subscribers = await getDigestSubscribers(db);
    const mine = subscribers.find((subscriber) => subscriber.userId === userId);

    expect(mine).toBeDefined();
    expect(mine?.email).toBe(`${userId}@invalid.test`);
  }, 60_000);

  // Reads the boundary back out of the database rather than constructing one.
  // Regression: the service used `new Date()` for the window while `createdAt`
  // is generated by Postgres. Those are different clocks — Neon measurably runs
  // ahead of this machine — so a job could be reported twice, or with the skew
  // reversed, never reported at all.
  async function currentBoundary(): Promise<Date> {
    const { db } = await import("@/lib/db");
    const { userSettings } = await import("@/lib/db/schema");
    const { eq } = await import("drizzle-orm");
    const { markDigestSent } = await import("./digest.db");

    await markDigestSent(db, userId);
    const [row] = await db
      .select({ at: userSettings.lastDigestSentAt })
      .from(userSettings)
      .where(eq(userSettings.userId, userId));
    return row.at!;
  }

  it("reports a job once and not again after the window moves", async () => {
    const { db } = await import("@/lib/db");
    const { getJobsSince } = await import("./digest.db");

    const windowStart = await currentBoundary();
    await addJob(`digest-a-${Date.now()}`, "React Developer");

    const firstRun = await getJobsSince(db, userId, windowStart);
    expect(firstRun.length).toBe(1);

    // Digest sent — the window advances, on the database's clock.
    const afterSend = await currentBoundary();
    expect(await getJobsSince(db, userId, afterSend)).toHaveLength(0);
  }, 60_000);

  it("picks up only what arrived after the last digest", async () => {
    const { db } = await import("@/lib/db");
    const { getJobsSince } = await import("./digest.db");

    const boundary = await currentBoundary();
    await addJob(`digest-b-${Date.now()}`, "Vue Developer");

    const since = await getJobsSince(db, userId, boundary);
    expect(since.length).toBe(1);
    expect(since[0].title).toBe("Vue Developer");
  }, 60_000);

  it("stores the boundary on the database clock, not the app clock", async () => {
    const boundary = await currentBoundary();
    // Proves the two clocks differ enough to matter — this is the actual bug.
    const skewMs = Math.abs(boundary.getTime() - Date.now());
    console.log(`[digest] app/database clock skew: ${skewMs}ms`);
    expect(boundary).toBeInstanceOf(Date);
  }, 60_000);

  it("ranks the new jobs so the digest can lead with the best", async () => {
    const { db } = await import("@/lib/db");
    const { getJobsSince } = await import("./digest.db");
    const { rankJobs } = await import("@/jobs/score-job");

    const boundary = new Date(Date.now() - 5 * 60_000);
    const all = await getJobsSince(db, userId, boundary);
    const ranked = rankJobs(all, { titles: ["React Developer"], locations: [] });

    expect(ranked.length).toBeGreaterThan(0);
    expect(ranked[0].score).toBeGreaterThanOrEqual(ranked[ranked.length - 1].score);
  }, 60_000);
});
