import { and, eq, gt, sql } from "drizzle-orm";
import type { Database } from "@/lib/db";
import { jobs, userSettings, users } from "@/lib/db/schema";
import { decryptOptionalSecret } from "@/lib/crypto/secret-box";

/** Accounts that asked for a daily run, with the address to send it to. */
export async function getDigestSubscribers(db: Database) {
  const rows = await db
    .select({
      userId: userSettings.userId,
      email: users.email,
      name: users.name,
      lastDigestSentAt: userSettings.lastDigestSentAt,
      digestChannels: userSettings.digestChannels,
      telegramBotToken: userSettings.telegramBotToken,
      telegramChatId: userSettings.telegramChatId,
    })
    .from(userSettings)
    .innerJoin(users, eq(users.id, userSettings.userId))
    .where(eq(userSettings.dailyDigestEnabled, true));

  // Stored encrypted, and the sender needs the real value.
  return rows.map((row) => ({
    ...row,
    telegramBotToken: decryptOptionalSecret(row.telegramBotToken),
  }));
}

/**
 * Jobs stored since the last digest.
 *
 * Keyed on `createdAt` — when we first saw it — rather than `postedAt`, which is
 * the employer's date and is often missing or backdated. The digest reports
 * what's new *to you*, not what's new to the world.
 */
export async function getJobsSince(db: Database, userId: string, since: Date) {
  return db
    .select()
    .from(jobs)
    .where(and(eq(jobs.userId, userId), gt(jobs.createdAt, since)));
}

/**
 * Moves the digest window to *the database's* current time.
 *
 * Deliberately takes no timestamp. `jobs.createdAt` is generated by Postgres, so
 * a boundary generated by the application is being compared against a different
 * clock — and they are not in sync. Measured against Neon, the database ran
 * ahead of the app server, which made jobs land after a boundary that was
 * supposedly set later, and they were reported a second time the next day. With
 * the skew in the other direction the same mistake silently loses jobs, which is
 * worse. Both sides now read the same clock.
 */
export async function markDigestSent(db: Database, userId: string) {
  await db
    .update(userSettings)
    .set({ lastDigestSentAt: sql`now()`, updatedAt: sql`now()` })
    .where(eq(userSettings.userId, userId));
}
